### ISSUE TITLE
.codacyrc get

### ISSUE THREAD

**Issue by niuzhi** [codacy/codacy-checkstyle#72]
can you give me a sample .codacyrc file for checkstyle？

**Comment by machadoit** [comment]
You can check [codacy-example-tool](https://github.com/codacy/codacy-example-tool) for more details on the file format. Here is an example that will look for the EmptyLineSeparator on the test.java file

*.codacyrc*

```
{
  "files" : ["test.java"],
  "tools":[
    {
      "name":"checkstyle",
      "patterns":[
        {
          "patternId":"EmptyLineSeparator"
        }
      ]
    }
  ]
}
```
