### ISSUE TITLE
[CY-5185] PackageName rule not working correctly

### ISSUE THREAD

**Issue by hendrikebbers** [codacy/codacy-checkstyle#85]
I have a checkstyle based issue in a pull request at Codacy that does not make sense to me. I have no idea if I should create an issue here or at checkstyle repo. The PR analysis can be found here: https://app.codacy.com/gh/adoptium/documentation-services/pullRequest?prid=8320146

**CheckStyle issue:** Checks that package names conform to a specified pattern. 
**Package name:** `net.adoptium.documentationservices.api`
From my point of view the given name is a valid package name. I even tried it with the given regex in the issue description by hand at https://regex101.com and the regex matches to the string.

Here is a screenshot of the issue:

<img width="1282" alt="checkstyle" src="https://user-images.githubusercontent.com/9443847/139403208-d8626cc1-09f0-4092-9cbe-c2fc207e4b83.png">

**Comment by machadoit** [comment]
Hi @hendrikebbers it seems that we do have a problem with storing some defaults of some patterns to be able to use the tool via Codacy UI. https://github.com/codacy/codacy-checkstyle/pull/86 should fix the issue when released

**Comment by machadoit** [comment]
It should now be working. We had an extra quote on the start and the end of the regex. If you check your code patterns, you should see it without it on the UI 
![image](https://user-images.githubusercontent.com/13315199/141833555-6b9c00be-cc84-41e0-a933-060518b84626.png)

Note that previous issues may not disappear from a previous PR, but that should be fixed going forward
